apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-backend
  template:
    metadata:
      labels:
        app: java-backend
    spec:
      containers:
      - name: java-backend
        image: gcr.io/devops-reto-tismart/mi-aplicacion-backend:1.0
        ports:
        - containerPort: 8080
